# Generated by Django 4.1.6 on 2023-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_details', '0002_course_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
